module.exports = function(){
    const express = require('express')
    const mongoose = require('mongoose')
    mongoose.connect('mongodb://localhost:27017/playground')
        .then(() => console.log(`connected to the data base`))
        .catch((err) => console.error(err.message))
        
    const {router : main , app} = require('./socket/io')
    const signUp = require('./router/user/signUp')
    const signIn = require('./router/user/signIn')
    const createRoom = require('./router/room/createRoom')
    const leaveRoom = require('./router/room/leaveRoom')
    const memberToAdmin = require('./router/room/memberToAdmin')
    const joinRoom = require('./router/room/joinRoom')
    const uploadMessageRoom = require('./router/message/uploadMessageRoom')
    const uploadMessagePrivate = require('./router/message/uploadMessagePrivate')
    const rewriteMessage = require('./router/message/rewriteMessage')
    const loadingMainPage = require('./router/loadMessage/loadingPage')
    const loadmorePrivateMessage = require('./router/loadMessage/loadingMoreMessage')
    const loadMoreMessageRoom = require('./router/loadMessage/loadingMoreMessageRoom')
    const emoji = require('./router/emoji/emoji')
    
    
    app.use(express.json())
    app.use('/' , main)
    app.use('/api/signup' , signUp)
    app.use('/api/signin' , signIn)
    app.use('/api/room/createroom' , createRoom)
    app.use('/api/room/leaveroom' , leaveRoom)
    app.use('/api/room/membertoadmin' , memberToAdmin)
    app.use('/api/room/joinroom' , joinRoom)
    app.use('/api/uploadmessage/room' , uploadMessageRoom)
    app.use('/api/uploadmessage/private' , uploadMessagePrivate)
    app.use('/api/rewritemessage' , rewriteMessage)
    app.use('/api/loading' , loadingMainPage)
    app.use('/api/loading/private' , loadmorePrivateMessage)
    app.use('/api/loading/room' , loadMoreMessageRoom)
    app.use('/api/message' , emoji)
    
}